sudo: true
dist: trusty
language: node_js
node_js:
  - "7"
cache:
  yarn: true
  apt: true
  directories:
    - frontend/node_modules
    - backend/vendor/bundle
env:
  - TEST_SUITE=backend
  - TEST_SUITE=frontend
  - TEST_SUITE=e2e
script:
  - ./travis_check
